urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
#from django.views.generic import generic

from cs564.models import *

urlpatterns = patterns('cs564.views',
        # display index page when user navigates to ctasims.com/cs564
        url(r'^$',  
            TemplateView.as_view(template_name="cs564/index.html"),
            name="index"),

        ### ANALYSIS pages ###
        # matches url using regex, then loads specified view from views.py
        # each one has name, so we can use that shortcut in HTML instead of full
        # URL. 
        url(r'^analysis/$',
            'analysis_list',
            name="analysis_list"),
        url(r'^analysis/add$',
            'analysis_list',
            name="analysis_add"),
        url(r'^analysis/(?P<pk>\d+)/$',
            'analysis_detail',
            name="analysis_detail"),
        url(r'analysis/(?P<pk>\d+)/delete/$',
            'analysis_delete',
            name="analysis_delete"),

        url(r'analysis/(?P<analysis_id>\d+)/component/add/$',
            'analysis_component_add',
            name="analysis_component_add"),

        url(r'analysis/(?P<analysis_id>\d+)/array/(?P<pv_array_id>\d+)/remove/$',
            'analysis_array_remove',
            name="analysis_array_remove"),
        url(r'analysis/(?P<analysis_id>\d+)/op/(?P<op_id>\d+)/remove/$',
            'analysis_op_remove',
            name="analysis_op_remove"),


        #### OBS PATH URLS ###

        url(r'^op/$',
            'observation_path_list',
            name="op_list"),
        url(r'^op/add$',
            'observation_path_list',
            name="op_add"),
        url(r'op/(?P<pk>\d+)/delete/$',
            'observation_path_delete',
            name="op_delete"),

        url(r'^op/(?P<pk>\d+)/$',
            'observation_path_detail',
            name="op_detail"),
        url(r'^op/(?P<pk>\d+)/update/$',
            'observation_path_detail',
            name="op_update"),
        url(r'op/(?P<pk>\d+)/coordinate/add/$',
            'observation_path_detail',
            name="op_coord_add"),
        url(r'op/(?P<op_id>\d+)/coordinate/(?P<coord_id>\d+)/delete/$',
            'observation_path_coordinate_delete',
            name="op_coord_delete"),


        ##### PANELS #####

        url(r'^panel/$',
            'panel_list',
            name="panel_list"),
        url(r'^panel/add$',
            'panel_list',
            name="panel_add"),
        url(r'panel/(?P<pk>\d+)/delete/$',
            'panel_delete',
            name="panel_delete"),


        #### PV ARRAYS ###

        url(r'^pv_array/$',
            'pv_array_list',
            name="pv_array_list"),
        url(r'^pv_array/add$',
            'pv_array_list',
            name="pv_array_add"),
        url(r'pv_array/(?P<pk>\d+)/delete/$',
            'pv_array_delete',
            name="pv_array_delete"),

        url(r'^pv_array/(?P<pk>\d+)/$',
            'pv_array_detail',
            name="pv_array_detail"),
        url(r'^pv_array/(?P<pk>\d+)/update/$',
            'pv_array_detail',
            name="pv_array_update"),
        url(r'pv_array/(?P<pk>\d+)/coordinate/add/$',
            'pv_array_detail',
            name="pv_array_coord_add"),
        url(r'pv_array/(?P<pv_array_id>\d+)/coordinate/(?P<coord_id>\d+)/delete/$',
            'pv_array_coordinate_delete',
            name="pv_array_coord_delete"),
        )


         #### when user clicks Site Stats. link. ###
urlpatterns += patterns('cs564.queries',
        url(r'^queries/$',
            'query_list',
            name="query_list"),
        )

models.py
from django.db import models
from django.core.urlresolvers import reverse


class ObservationPath(models.Model):
    """
    obs path model represents one or more coordinates from which PV array is viewed.
    Goal is to check these points against array for glare.
    """
    name = models.CharField(help_text='Name of observation', max_length=30)
    direction = models.DecimalField(help_text='direction (if flight path)',
            max_digits=5, decimal_places=2, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)


class SunPath(models.Model):
    """
    Sun path is entire trajectory of sun movement across sky, for one year.
    lat/lng represents observatoin point from which we view sun.
    """
    observer_lat = models.DecimalField(help_text='Observer latitude',
            max_digits=7, decimal_places=5)
    observer_lng = models.DecimalField(help_text='Observer longitude',
            max_digits=8, decimal_places=5)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        # This is how Django handles composite primary keys
        unique_together = (("observer_lat", "observer_lng"),)


class SunPosition(models.Model):
    """
    Single location of sun at given time.
    """
    dt = models.DateTimeField()
    sun_path = models.ForeignKey(SunPath, on_delete=models.CASCADE)
    azimuth = models.DecimalField(max_digits=6, decimal_places=3)
    elevation = models.DecimalField(max_digits=5, decimal_places=3)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        unique_together = (("dt", "sun_path"),)


class Panel(models.Model):
    """
    PV arrays are comprised of panels.
    """
    name = models.CharField(max_length=100)
    manufacturer = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    reflectivity = models.DecimalField(max_digits=4, decimal_places=3, blank=True, null=True)
    index_of_refrac = models.DecimalField(max_digits=10, decimal_places=8, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        unique_together = (("name", "manufacturer"),)


class PVArray(models.Model):
    """
    Photovoltaic array installation.
    We want to know if these cause glare when viewed from observer position.
    """
    name = models.CharField(max_length=100)
    orientation = models.DecimalField(max_digits=6, decimal_places=3, default=180)
    tilt = models.DecimalField(max_digits=5, decimal_places=3, default=0)
    height = models.DecimalField(max_digits=10, decimal_places=3, default=0)
    panel = models.ForeignKey(Panel, help_text='Type of panel', null=True,
            on_delete=models.SET_NULL)
    sun_path = models.ForeignKey(SunPath, blank=True, null=True,
            on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)


class Coordinate(models.Model):
    """
    Generic latitude/longitude coordinate.
    Used by observation to designate place from which we view PV array.
    Also used by PV array to designate vertices of array footprint.
    """
    latitude = models.DecimalField(max_digits=7, decimal_places=5)
    longitude = models.DecimalField(max_digits=8, decimal_places=5)
    elevation = models.DecimalField(help_text='Ground elevation (m)', max_digits=10, decimal_places=2)
    height = models.DecimalField(help_text='Height above ground (m)', max_digits=10, decimal_places=2, default=0)
    path = models.ForeignKey(ObservationPath, null=True, blank=True,
            on_delete=models.CASCADE)
    pv_array = models.ForeignKey(PVArray, null=True, blank=True,
            on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        unique_together = (
                ("latitude", "longitude", "height", "path"),
                ("latitude", "longitude", "height", "pv_array"),
                )

    def get_absolute_url(self):
        return reverse('coordinate_detail', kwargs={'pk': self.pk})


class Analysis(models.Model):
    """
    An analysis represents computation of specified arrays and observations,
    and whether or not glare is present.
    """
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)


class AnalysisComponent(models.Model):
    """
    Use component to add array or obs path to given analysis.
    """
    analysis = models.ForeignKey(Analysis,
            on_delete=models.CASCADE)
    path = models.ForeignKey(ObservationPath, null=True, blank=True,
            on_delete=models.SET_NULL)
    pv_array = models.ForeignKey(PVArray, null=True, blank=True,
            on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        unique_together = (
                ('analysis', 'path', 'pv_array'),
                )

templates/cs564/analysis_detail.html
{% extends "cs564/base.html" %}

{% block title %}Analysis Detail{% endblock %}

{% block content %}

<ul class="breadcrumb">
  <li><a href="{% url 'cs564:index' %}">Main</a> <span class="divider">/</span></li>
  <li><a href="{% url 'cs564:analysis_list' %}">Analyses</a> <span class="divider">/</span></li>
  <li class="active">Analysis: {{ analysis.name }}</li>
</ul>


<div class="page-header">
  <h1>Analysis: {{ analysis.name }}</h1>
</div>


<div class="row">
  <div class="span12">
    <form class="form-inline" action="{% url 'cs564:analysis_detail' analysis.id %}" method="POST">
      {% csrf_token %}
      {{ a_form.non_field_errors }}
      <div class="row">
        <div class="span2"><strong>Name</strong></div>
        <div class="span2"><strong>Description</strong></div>
      </div>
      <div class="row">
        <div class="span2">
          <input type="text" id="id_name" class="input-small" name="name"
            value="{{ analysis.name }}"/>
        </div>
        <div class="span2">
          <input type="text" id="id_description" class="input-small" name="description"
            value="{{ analysis.description }}"/>
          </div>

        <div class="span2">
          <button type="submit" class="btn">Update</button>
        </div>
      </div>
      <div class="row">
        <div class="span2">{{ a_form.name.errors }}</div>
        <div class="span2">{{ a_form.description.errors }}</div>
      </div>
            
      <input type="hidden" name="created_at" id="id_created_at" value="{{ analysis.created_at }}" />
    </form>
  </div>
</div>


<div class="page-header">
  <h3>PV Arrays</h3>
</div>
<div class="row">
  <div class="span8">
    {% if a_array_list %}
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Path id</th>
          <th>Name</th>
          <th>Orientation</th>
          <th>Tilt</th>
          <th>Height</th>
          <th>Panel</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for a_array in a_array_list %}
        <tr>
          <td>
            <a href="{% url 'cs564:pv_array_detail' a_array.id %}">{{ a_array.id }}</a>
          </td>
          <td>{{ a_array.name }}</td>
          <td>{{ a_array.orientation }}</td>
          <td>{{ a_array.tilt }}</td>
          <td>{{ a_array.height }}</td>
          <td>{{ a_array.panel.name }}</td>
          <td>
            <form action="{% url 'cs564:analysis_array_remove' analysis.id a_array.id %}"
              method="POST" style="margin:0px;">
              {% csrf_token %}
              <button type="submit" class="btn btn-link">Remove from analysis</button>
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    </ul>
    {% else %}
    <p>No PV arrays found for this analysis.</p>
    {% endif %}
  </div>
</div>

<br />
<br />
<div class="row">
  <div class="span12">
    <form action="{% url 'cs564:analysis_component_add' analysis.id %}" class="form-inline" method="post">
      {% csrf_token %}
      {{ component_form.non_field_errors }}
      <label for="array-id_pv_array">Add PV array to analysis:
        <select class="span2" name="array-pv_array" id="id_array-pv_array">
          {% for pv_array in pv_array_list %}
          <option value="{{ pv_array.id }}">{{ pv_array.name }}</option>
          {% endfor %}
        </select>
      </label>
      <button type="submit" class="btn">Add</button>
      <div class="row">
        <div class="span2">{{ component_form.pv_array.errors }}</div>
      </div>
      <input type="hidden" name="array-analysis" id="id_array-analysis" value="{{ analysis.id }}" />
    </form>
  </div>
</div>


<div class="page-header">
  <h3>Observation paths</h3>
</div>
<div class="row">
  <div class="span8">
    {% if a_op_list %}
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Path id</th>
          <th>Name</th>
          <th>Direction</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for op in a_op_list %}
        <tr>
          <td>
            <a href="{% url 'cs564:op_detail' analysis.id %}">{{ op.id }}</a>
          </td>
          <td>{{ op.name }}</td>
          <td>{{ op.direction }}</td>
          <td>
            <form action="{% url 'cs564:analysis_op_remove' analysis.id op.id %}"
              method="POST" style="margin:0px;">
              {% csrf_token %}
              <button type="submit" class="btn btn-link">Remove from analysis</button>
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    </ul>
    {% else %}
    <p>No observations found for this analysis.</p>
    {% endif %}
  </div>
</div>

<br />
<br />
<div class="row">
  <div class="span12">
    <form action="{% url 'cs564:analysis_component_add' analysis.id %}" class="form-inline" method="post">
      {% csrf_token %}
      {{ component_form.non_field_errors }}
      <label>Add observation to analysis:
        <select class="span2" name="op-path" id="path-id_path">
          {% for op in op_list %}
          <option value="{{ op.id }}">{{ op.name }}</option>
          {% endfor %}
        </select>
      </label>
      <button type="submit" class="btn">Add</button>
      <div class="row">
        <div class="span2">{{ component_form.path.errors }}</div>
      </div>
      <input type="hidden" name="op-analysis" id="op-id_analysis" value="{{ analysis.id }}" />
    </form>
  </div>
</div>

{% endblock %}

templates/cs564/panel_list.html
{% extends "cs564/base.html" %}

{% block title %}Panels{% endblock %}

{% block content %}

<ul class="breadcrumb">
  <li><a href="{% url 'cs564:index' %}">Main</a> <span class="divider">/</span></li>
  <li class="active">Panels</li>
</ul>

<div class="page-header">
  <h1>Panels</h1>
</div>
<div class="row">
  <div class="span8" style="height:300px;overflow:auto;">
    {% if panel_list %}
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Panel id</th>
          <th>Name</th>
          <th>Manufacturer</th>
          <th>Description</th>
          <th>Reflectivity</th>
          <th>Index of Refraction</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for panel in panel_list %}
        <tr>
          <td>{{ panel.id }}</td>
          <td>{{ panel.name }}</td>
          <td>{{ panel.manufacturer }}</td>
          <td>{{ panel.description }}</td>
          <td>{{ panel.reflectivity }}</td>
          <td>{{ panel.index_of_refrac }}</td>
          <td>
            <form action="{% url 'cs564:panel_delete' panel.id %}"
              method="POST" style="margin:0px;">
              {% csrf_token %}
              <button type="submit" class="btn btn-link">delete</button>
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    </ul>
    {% else %}
    <p>No panels found. Add some!</p>
    {% endif %}
  </div>
</div>


<div class="page-header">
  <h2>Add Panel</h2>
</div>
<div class="row">
  <div class="span12">
    <form action="{% url 'cs564:panel_add' %}" class="form-inline" method="post">
      {% csrf_token %}
      {{ panel_form.non_field_errors }}
      <div class="row">
        <div class="span2"><strong>Name</strong></div>
        <div class="span2"><strong>Manufacturer</strong></div>
        <div class="span2"><strong>Description</strong></div>
        <div class="span2"><strong>Reflectivity</strong></div>
        <div class="span2"><strong>Index of refraction</strong></div>
      </div>
      <div class="row">
        <div class="span2">
          <input type="text" id="id_name" class="input-small" name="name"
            value="{{ panel_form.name.value|default_if_none:"" }}"/>
        </div>
        <div class="span2">
          <input type="text" id="id_manufacturer" class="input-small" name="manufacturer"
            value="{{ panel_form.manufacturer.value|default_if_none:"" }}"/>
        </div>
        <div class="span2">
          <input type="text" id="id_description" class="input-small" name="description"
            value="{{ panel_form.description.value|default_if_none:"" }}"/>
        </div>
        <div class="span2">
          <input type="text" id="id_reflectivity" class="input-small" name="reflectivity"
            value="{{ panel_form.reflectivity.value|default_if_none:"" }}"/>
        </div>
        <div class="span2">
          <input type="text" id="id_index_of_refrac" class="input-small" name="index_of_refrac"
            value="{{ panel_form.index_of_refrac.value|default_if_none:"" }}"/>
        </div>
        <div class="span2">
          <button type="submit" class="btn">Add</button>
        </div>
      </div>
      <div class="row">
        <div class="span2">{{ panel_form.name.errors }}</div>
        <div class="span2">{{ panel_form.manufacturer.errors }}</div>
        <div class="span2">{{ panel_form.description.errors }}</div>
        <div class="span2">{{ panel_form.reflectivity.errors }}</div>
        <div class="span2">{{ panel_form.index_of_refrac.errors }}</div>
      </div>
    </form>
  </div>
</div>


{% endblock %}

templates/cs564/pvarray_detail.html
{% extends "cs564/base.html" %}

{% block title %}PV Array Detail{% endblock %}

{% block content %}

<ul class="breadcrumb">
  <li><a href="{% url 'cs564:index' %}">Main</a> <span class="divider">/</span></li>
  <li><a href="{% url 'cs564:pv_array_list' %}">PV Arrays</a> <span class="divider">/</span></li>
  <li class="active">{{ pv_array.name }}</li>
</ul>


<div class="page-header">
  <h1>{{ pv_array.name }}</h1>
</div>

<div class="row">
  <div class="span12">
    <form class="form-inline" action="{% url 'cs564:pv_array_update' pv_array.id %}" method="POST">
      {% csrf_token %}
      {{ p_form.non_field_errors }}
      {{ p_form.sun_path.errors }}
      <div class="row">
        <div class="span2"><strong>Name</strong></div>
        <div class="span2"><strong>Orientation</strong></div>
        <div class="span2"><strong>Tilt</strong></div>
        <div class="span2"><strong>Height</strong></div>
        <div class="span2"><strong>Panel type</strong></div>
      </div>
      <div class="row">
        <div class="span2">
          <input type="text" id="id_name" class="input-small" name="name"
            value="{{ pv_array.name }}"/>
        </div>
        <div class="span2">
          <div class="input-append">
            <input type="text" id="id_orientation" class="input-small" name="orientation"
              value="{{ pv_array.orientation }}"/>
              <span class="add-on">deg</span>
          </div>
        </div>
        <div class="span2">
          <div class="input-append">
            <input type="text" id="id_tilt" class="input-small" name="tilt"
            value="{{ pv_array.tilt }}"/>
              <span class="add-on">deg</span>
          </div>
        </div>
        <div class="span2">
          <div class="input-append">
            <input type="text" id="id_height" class="input-small" name="height"
            value="{{ pv_array.height }}"/>
              <span class="add-on">ft</span>
          </div>
        </div>
        <div class="span2">
          <select class="span2" name="panel" id="id_panel">
            {% for panel in panel_list %}
              {% if panel.id == pv_array.panel.id %}
              <option value="{{ panel.id }}" selected="selected">{{ panel.name }}</option>
              {% else %}
              <option value="{{ panel.id }}">{{ panel.name }}</option>
              {% endif %}
            {% endfor %}
          </select>
        </div>
        <input type="hidden" id="id_sun_path" name="sun_path" value="{{ pv_array.sun_path|default_if_none:"" }}" />
        <div class="span2">
          <button type="submit" class="btn">Update</button>
        </div>
      </div>
      <div class="row">
        <div class="span2">{{ p_form.name.errors }}</div>
        <div class="span2">{{ p_form.orientation.errors }}</div>
        <div class="span2">{{ p_form.tilt.errors }}</div>
        <div class="span2">{{ p_form.height.errors }}</div>
        <div class="span2">{{ p_form.panel.errors }}</div>
      </div>
            
      <input type="hidden" name="created_at" id="id_created_at" value="{{ pv_array.created_at }}" />
    </form>
  </div>
</div>


<div class="page-header">
  <h2>PV array coordinates</h2>
</div>
<div class="row">
  <div class="span8">
    {% if coord_list %}
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>latitude</th>
          <th>longitude</th>
          <th>elevation</th>
          <th>height</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% if coord_list %}
        {% for coordinate in coord_list %}
        <tr>
          <td>{{ coordinate.latitude }}</td>
          <td>{{ coordinate.longitude }}</td>
          <td>{{ coordinate.elevation }}</td>
          <td>{{ coordinate.height }}</td>
          <td>
            <form action="{% url 'cs564:pv_array_coord_delete' pv_array.id coordinate.id %}"
              method="POST" style="margin:0px;">
              {% csrf_token %}
              <button type="submit" class="btn btn-link">delete</button>
            </form>
          </td>
        </tr>
        {% endfor %}
        {% else %}
        {% endif %}
      </tbody>
    </table>
    {% else %}
    <p>No coordinates found. Add some!</p>
    {% endif %}
  </div>
</div>


<div class="page-header">
  <h2>Add coordinate</h2>
</div>
<div class="row">
  <div class="span11">
    <form action="{% url 'cs564:pv_array_coord_add' pv_array.id %}" class="form-inline" method="post">
      {% csrf_token %}
      {{ c_form.non_field_errors }}
      {{ c_form.path.errors }}
      {{ c_form.array.errors }}
      <div class="row">
        <div class="span2"><strong>Latitude</strong></div>
        <div class="span2"><strong>Longitude</strong></div>
        <div class="span2"><strong>Elevation</strong></div>
        <div class="span2"><strong>Height</strong></div>
      </div>
      <div class="row">
        <div class="span2">
          <div class="input-append">
          <input type="text" id="id_c-latitude" class="input-small" name="c-latitude"
            value="{{ c_form.latitude.value|default_if_none:"" }}"/>
            <span class="add-on">deg</span>
          </div>
        </div>
        <div class="span2">
          <div class="input-append">
          <input type="text" id="id_c-longitude" class="input-small" name="c-longitude"
            value="{{ c_form.longitude.value|default_if_none:"" }}"/>
            <span class="add-on">deg</span>
          </div>
        </div>
        <div class="span2">
          <div class="input-append">
          <input type="text" id="id_c-elevation" class="input-mini" name="c-elevation"
            value="{{ c_form.elevation.value|default_if_none:"" }}"/>
            <span class="add-on">m</span>
          </div>
        </div>
        <div class="span2">
          <div class="input-append">
          <input type="text" id="id_c-height" class="input-mini" name="c-height"
            value="{{ c_form.height.value|default_if_none:"" }}"/>
            <span class="add-on">m</span>
          </div>
        </div>
        <div class="span2">
          <button type="submit" class="btn">Add</button>
        </div>
      </div>
      <div class="row">
        <div class="span2">{{ c_form.latitude.errors }}</div>
        <div class="span2">{{ c_form.longitude.errors }}</div>
        <div class="span2">{{ c_form.elevation.errors }}</div>
        <div class="span2">{{ c_form.height.errors }}</div>
      </div>
      <input type="hidden" id="id_c-path" name="c-path" value=""/>
      <input type="hidden" id="id_c-pv_array" name="c-pv_array" value="{{ pv_array.id }}"/>
    </form>
  </div>
</div>

{% endblock %}

templates/cs564/pvarray_list.html
{% extends "cs564/base.html" %}

{% block title %}PV Arrays{% endblock %}

{% block content %}

<ul class="breadcrumb">
  <li><a href="{% url 'cs564:index' %}">Main</a> <span class="divider">/</span></li>
  <li class="active">PV Arrays</li>
</ul>

<div class="page-header">
  <h1>PV Arrays</h1>
</div>
<div class="row">
  <div class="span8"  style="height:300px;overflow:auto;">
    {% if pv_array_list %}
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Path id</th>
          <th>Name</th>
          <th>Orientation</th>
          <th>Tilt</th>
          <th>Height</th>
          <th>Panel Type</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for pv_array in pv_array_list %}
        <tr>
          <td>
            <a href="{% url 'cs564:pv_array_detail' pv_array.id %}">{{ pv_array.id }}</a>
          </td>
          <td>{{ pv_array.name }}</td>
          <td>{{ pv_array.orientation }}</td>
          <td>{{ pv_array.tilt }}</td>
          <td>{{ pv_array.height }}</td>
          <td>{{ pv_array.panel.manufacturer }} - {{ pv_array.panel.name }}</td>
          <td>
            <form action="{% url 'cs564:pv_array_delete' pv_array.id %}"
              method="POST" style="margin:0px;">
              {% csrf_token %}
              <button type="submit" class="btn btn-link">delete</button>
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    </ul>
    {% else %}
    <p>No PV arrays found. Add some!</p>
    {% endif %}
  </div>
</div>


<div class="page-header">
  <h2>Add PV array</h2>
</div>
<div class="row">
  <div class="span12">
    <form action="{% url 'cs564:pv_array_add' %}" class="form-inline" method="post">
      {% csrf_token %}
      {{ pv_array_form.non_field_errors }}
      {{ pv_array_form.sun_path.errors }}
      <div class="row">
        <div class="span2"><strong>Name</strong></div>
        <div class="span2"><strong>Orientation</strong></div>
        <div class="span2"><strong>Tilt</strong></div>
        <div class="span2"><strong>Height</strong></div>
        <div class="span2"><strong>Panel type</strong></div>
      </div>
      <div class="row">
        <div class="span2">
          <input type="text" id="id_name" class="input-small" name="name"
            value="{{ pv_array_form.name.value|default_if_none:"" }}"/>
        </div>
        <div class="span2">
          <div class="input-append">
            <input type="text" id="id_orientation" class="input-small" name="orientation"
              value="{{ pv_array_form.orientation.value|default_if_none:"" }}"/>
              <span class="add-on">deg</span>
          </div>
        </div>
        <div class="span2">
          <div class="input-append">
            <input type="text" id="id_tilt" class="input-small" name="tilt"
              value="{{ pv_array_form.tilt.value|default_if_none:"" }}"/>
              <span class="add-on">deg</span>
          </div>
        </div>
        <div class="span2">
          <div class="input-append">
            <input type="text" id="id_height" class="input-small" name="height"
              value="{{ pv_array_form.height.value|default_if_none:"" }}"/>
              <span class="add-on">ft</span>
          </div>
        </div>
        <div class="span2">
          <select class="span2" name="panel" id="id_panel">
            {% for panel in panel_list %}
            <option value="{{ panel.id }}">{{ panel.name }}</option>
            {% endfor %}
          </select>
        </div>
        <input type="hidden" id="id_sun_path" name="sun_path" value="" />
        <div class="span2">
          <button type="submit" class="btn">Add</button>
        </div>
      </div>
      <div class="row">
        <div class="span2">{{ pv_array_form.name.errors }}</div>
        <div class="span2">{{ pv_array_form.orientation.errors }}</div>
        <div class="span2">{{ pv_array_form.tilt.errors }}</div>
        <div class="span2">{{ pv_array_form.height.errors }}</div>
        <div class="span2">{{ pv_array_form.panel.errors }}</div>
      </div>
    </form>
  </div>
</div>


{% endblock %}